name: Auto Generate Blog Posts

on:
  schedule:
    # 日本時間で毎朝 3:00 に実行（UTC 18:00）
    - cron: '0 18 * * *'
  workflow_dispatch:  # 手動トリガー用

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # GITHUB_TOKEN で push できるように

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv pytrends

      - name: Create .env
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Generate posts
        run: python generate_posts.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/content/blog/*.md
          git diff --quiet && echo "No new posts to commit." || git commit -m "chore: auto-generate posts"

      - name: Push to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
