name: Auto Generate Blog Posts

# 手動＋スケジュールで走らせる
on:
  workflow_dispatch:
  schedule:
    # 日本時間18:00 = UTC09:00 に毎日
    - cron:  '0 9 * * *'

jobs:
  generate-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install openai pytrends python-dotenv
      - name: Run generator
        run: python generate_posts.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit & push new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/content/blog/*.md
          git commit -m "chore: auto-generate posts (cron)" || echo "no changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
